#guest
#Tue Apr 07 03:10:51 GMT 2026
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.viewedParameters=false
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.viewedSource=true
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.numVisits=138
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.viewedCookies=false
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.completed=false
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.viewedLessonPlan=false
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.viewedHtml=false
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.currentStage=2
LAB\:\ \uC5ED\uD560\ \uAE30\uBC18\ \uC5D1\uC138\uC2A4\ \uC81C\uC5B4.maxHintLevel=6
