#guest
#Mon Mar 23 17:25:07 GMT 2026
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedLessonPlan=false
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.numVisits=10
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedSource=false
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.completed=true
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedCookies=false
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.currentStage=2
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedParameters=false
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.maxHintLevel=0
Numeric\ SQL\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedHtml=false
