#guest
#Mon Mar 23 17:33:35 GMT 2026
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .completed=true
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .currentStage=1
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .maxHintLevel=0
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .viewedLessonPlan=false
stage=2
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .viewedCookies=false
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .viewedSource=false
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .viewedParameters=false
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .viewedHtml=false
\uC5B4\uB5BB\uAC8C\ \uBB38\uC790\uC5F4\ SQL\ \uC778\uC81D\uC158\uC744\ \uC2E4\uD589\uD558\uB294\uAC00?\ .numVisits=15
