#guest
#Mon May 25 19:40:15 KST 2009
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.viewedHtml=false
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.currentStage=1
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.maxHintLevel=0
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.viewedParameters=false
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.numVisits=0
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.completed=false
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.viewedSource=false
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.viewedCookies=false
\uC6F9\ \uC11C\uBE44\uC2A4\ SQL\ \uC778\uC81D\uC158.viewedLessonPlan=false
