#guest
#Tue Apr 07 02:52:35 GMT 2026
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.viewedParameters=false
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.viewedSource=false
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.viewedHtml=false
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.numVisits=0
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.viewedCookies=false
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.completed=false
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.viewedLessonPlan=false
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.currentStage=1
\uACBD\uB85C\uC5D0\ \uAE30\uCD08\uD55C\ \uC561\uC138\uC2A4\ \uC81C\uC5B4\ \uCCB4\uACC4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD560\ \uC218\ \uC788\uB294\uAC00.maxHintLevel=0
