#guest
#Mon Mar 23 17:22:39 GMT 2026
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedHtml=false
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedCookies=false
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedParameters=false
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedSource=false
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.numVisits=10
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.completed=false
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.currentStage=1
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.maxHintLevel=0
\uBA85\uB839\uC5B4\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedLessonPlan=false
