#guest
#Mon Mar 23 17:03:03 GMT 2026
\uC778\uCF54\uB529\ \uAE30\uBCF8.numVisits=0
\uC778\uCF54\uB529\ \uAE30\uBCF8.completed=false
\uC778\uCF54\uB529\ \uAE30\uBCF8.currentStage=1
\uC778\uCF54\uB529\ \uAE30\uBCF8.viewedLessonPlan=false
\uC778\uCF54\uB529\ \uAE30\uBCF8.maxHintLevel=0
\uC778\uCF54\uB529\ \uAE30\uBCF8.viewedParameters=false
\uC778\uCF54\uB529\ \uAE30\uBCF8.viewedSource=false
\uC778\uCF54\uB529\ \uAE30\uBCF8.viewedCookies=false
\uC778\uCF54\uB529\ \uAE30\uBCF8.viewedHtml=false
