#guest
#Mon May 25 19:40:24 KST 2009
\uB3C4\uC804\!\!.numVisits=0
\uB3C4\uC804\!\!.viewedSource=false
\uB3C4\uC804\!\!.completed=false
\uB3C4\uC804\!\!.viewedLessonPlan=false
\uB3C4\uC804\!\!.currentStage=1
\uB3C4\uC804\!\!.viewedHtml=false
\uB3C4\uC804\!\!.maxHintLevel=0
\uB3C4\uC804\!\!.viewedParameters=false
\uB3C4\uC804\!\!.viewedCookies=false
