#guest
#Wed Apr 01 03:26:42 GMT 2026
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.viewedLessonPlan=false
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.viewedCookies=false
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.viewedSource=true
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.completed=true
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.viewedParameters=false
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.currentStage=1
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.numVisits=41
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.maxHintLevel=3
\uC778\uC99D\ \uCFE0\uD0A4\uB97C\ \uC5B4\uB5BB\uAC8C\ \uC704\uC870\uD558\uB294\uAC00.viewedHtml=false
