#guest
#Mon May 25 19:39:59 KST 2009
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.viewedSource=false
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.viewedParameters=false
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.currentStage=1
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.viewedLessonPlan=false
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.numVisits=0
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.completed=false
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.maxHintLevel=1
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.viewedCookies=false
SOAP\ request\uB294\ \uC5B4\uB5BB\uAC8C\ \uB9CC\uB4E4\ \uC218\ \uC788\uB294\uAC00.viewedHtml=false
