#guest
#Mon Mar 23 17:03:55 GMT 2026
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedLessonPlan=false
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedHtml=false
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedSource=false
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedCookies=false
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedParameters=false
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.numVisits=0
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.completed=true
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.currentStage=1
\uB9E4\uAC1C\uBCC0\uC218\ \uC778\uC81D\uC158\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.maxHintLevel=0
