#guest
#Fri Sep 04 05:56:34 GMT 2015
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.viewedLessonPlan=false
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.maxHintLevel=4
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.numVisits=4
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.viewedSource=true
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.completed=false
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.viewedParameters=false
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.viewedHtml=false
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.currentStage=1
\uC6D0\uACA9\ \uAD00\uB9AC\uC790\ \uC561\uC138\uC2A4.viewedCookies=false
