#guest
#Tue Apr 07 02:50:54 GMT 2026
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.viewedParameters=false
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.viewedHtml=false
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.completed=false
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.viewedSource=true
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.viewedCookies=false
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.numVisits=31
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.viewedLessonPlan=false
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.currentStage=1
\uD074\uB77C\uC774\uC5B8\uD2B8\ \uCE21\uC5D0\uC11C\ \uC790\uBC14\uC2A4\uD06C\uB9BD\uD2B8\ \uD655\uC778\uC744\ \uC5B4\uB5BB\uAC8C\ \uC6B0\uD68C\uD558\uB294\uAC00.maxHintLevel=3
