#guest
#Fri Sep 04 05:32:35 GMT 2015
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.numVisits=4
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedSource=false
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.completed=false
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.currentStage=1
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedLessonPlan=false
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedParameters=false
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.maxHintLevel=2
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedHtml=false
\uC800\uC7A5\ \uD06C\uB85C\uC2A4\ \uC0AC\uC774\uD2B8\ \uC2A4\uD06C\uB9BD\uD305\uC744\ \uC5B4\uB5BB\uAC8C\ \uC2E4\uD589\uD558\uB294\uAC00.viewedCookies=false
