#guest
#Wed Apr 01 02:26:24 GMT 2026
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.currentStage=1
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.viewedLessonPlan=false
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.maxHintLevel=1
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.numVisits=13
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.completed=true
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.viewedCookies=false
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.viewedSource=true
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.viewedHtml=false
\uC228\uACA8\uC9C4\ \uD544\uB4DC\ \uACF5\uACA9\ \uBC29\uBC95.viewedParameters=false
