#guest
#Wed Jun 24 21:26:36 KST 2009
\uC81C\uD488\ \uC815\uBCF4.numVisits=0
\uC81C\uD488\ \uC815\uBCF4.completed=true
\uC81C\uD488\ \uC815\uBCF4.currentStage=1
\uC81C\uD488\ \uC815\uBCF4.viewedParameters=false
\uC81C\uD488\ \uC815\uBCF4.maxHintLevel=0
\uC81C\uD488\ \uC815\uBCF4.viewedCookies=false
\uC81C\uD488\ \uC815\uBCF4.viewedHtml=false
\uC81C\uD488\ \uC815\uBCF4.viewedLessonPlan=false
\uC81C\uD488\ \uC815\uBCF4.viewedSource=false
