# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1133305109);
user_pref("app.update.lastUpdateTime.background-update-timer", 1133305108);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.download.manager.retention", 1);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days", 0);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.preferences.privacy.selectedTabIndex", 0);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.8");
user_pref("extensions.lastAppVersion", "1.5");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("nglayout.debug.disable_xul_cache", false);
user_pref("pref.privacy.disable_button.clear_cache", false);
user_pref("pref.privacy.disable_button.clear_cookies", false);
